arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: all

plugins:
  - "prettier-plugin-solidity"
overrides:
  - files: "*.sol"
    parser: "solidity-parse"
    options:
      tabWidth: 4
