name: Paraswap Install, lint, test and deploy pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install-compile-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY}}
      MNEMONIC: ${{ secrets.MNEMONIC}}

    steps:
      - name: Checkout Use Node.js ${{ matrix.node-version}}
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: npm-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: npm-v2-
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Compile
        run: |
          yarn compile
      - name: Lint
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
